
FROM node:22-slim

RUN apt update && apt install -y openssl procps
RUN npm install -g ts-node
RUN npm i -g @nestjs/cli

# USER node

WORKDIR /home/node/app

COPY package.json package-lock.json ./
COPY src ./src
COPY tsconfig.json tsconfig.build.json nest-cli.json ./
COPY .env.example ./
COPY start.sh ./
RUN chmod +x start.sh

CMD [ "/bin/bash", "start.sh" ]